
services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # Event Listeners
    #
    Pimcore\Bundle\GoogleMarketingBundle\EventListener\IndexSettingsListener:
        tags:
            - { name: kernel.event_listener, event: pimcore.admin.indexAction.settings, method: indexSettings }
